### ISSUE TITLE
Fossil Multiplier

### ISSUE THREAD

**Issue by NickRyder** [Sectoidfodder/PoETheoryCraft#3]
There is evidence that "increasing" fossil multipliers don't stack multiplicatively.

One can check this in game by using three fossils on an item which has a mod positively influenced by all three. The weighting would be multiplied by 1000, dwarfing all of the other mods.

**Comment by Sectoidfodder** [comment]
Do you know of any tests done for this?

Having an overwhelming weight would just mean that mod group gets picked on every roll of an item.  Some fossil mods show up nearly every time with just a 10x multiplier, so it'd take a lot of rolls to tell the difference between the "nearly always" of 30x and the "nearly always" of a 1000x multiplier.
