### ISSUE TITLE
request: raise masscraft limit to more than 5000

### ISSUE THREAD

**Issue by zerger3** [Sectoidfodder/PoETheoryCraft#5]

**Comment by zerger3** [comment]
to get a proper probability to hit certain mods i did like 20 times 5000 and added the numbers by hand. it would be nice if i could raise to like 100k and see the probability

**Comment by Sectoidfodder** [comment]
Already done, along with performance improvements.  Will be in next release.

It's also a number you can edit in TheoryCraft.exe.config to whatever.
