### ISSUE TITLE
Program crash on using weights

### ISSUE THREAD

**Issue by ghost** [Sectoidfodder/PoETheoryCraft#8]
I've encountered a similar issue as #7 however using a different workflow; however I don't have any empty groups and it crashes on the try currency button. 

A quick video of what I'm getting is here https://youtu.be/KSF3ptLTRKM

If you need any further information or there are logs I can send just let me know.

**Comment by Sectoidfodder** [comment]
That's the same issue as #7.  You didn't specify a weight so that line is ignored, resulting in an empty condition.

Should already be fixed in 0.5.1
